#!/usr/bin/env bash
# ===========================================================================
# lain installer
#
# Installs the lain media server and/or the lain-desktop client on Linux.
#   server:  https://github.com/enrell/lain           (Go, image ghcr.io/enrell/lain)
#   desktop: https://github.com/enrell/lain-desktop   (Qt6/QML + libmpv)
#
# Interactive menu by default; every choice is also available as a flag
# (see --help). Existing Compose files are reused unless regeneration is chosen.
#
# No personal data is embedded; all paths are derived from $HOME or flags.
# ===========================================================================
set -euo pipefail

# --- Constants -------------------------------------------------------------

GENERATED_MARKER='Generated by lain install.sh'
SERVER_REPO='enrell/lain'
DESKTOP_REPO='enrell/lain-desktop'
GITHUB='https://github.com'
DOCKER_IMAGE='ghcr.io/enrell/lain'
DEFAULT_VERSION='latest'
CONTAINER_PORT='9360'
CONTAINER_DATA_DIR='/data'

: "${HOME:?HOME must be set to run the installer}"
DEFAULT_PORT='9360'
DEFAULT_DATA_DIR="${HOME}/.local/share/lain"
DEFAULT_INSTALL_DIR="${HOME}/.local/bin"
DEFAULT_COMPOSE_DIR="${HOME}/.lain"
DEFAULT_MEDIA_DIR="${HOME}/Videos"

# --- Globals ---------------------------------------------------------------

SCRIPT_PATH=''
ASSUME_YES=0
INTERACTIVE=1
UNINSTALL=0
UNINSTALL_LEVEL=''
PURGE_DATA=0
REMOVE_IMAGE=0
SERVER=''
DESKTOP=''
MODE=''
VERSION="$DEFAULT_VERSION"
VERSION_SET=0
PORT="$DEFAULT_PORT"
PORT_SET=0
DATA_DIR="$DEFAULT_DATA_DIR"
DATA_SET=0
INSTALL_DIR="$DEFAULT_INSTALL_DIR"
INSTALL_SET=0
COMPOSE_DIR="$DEFAULT_COMPOSE_DIR"
COMPOSE_SET=0
REUSE_COMPOSE=0
MEDIA_DIRS=()
MEDIA_GIVEN=0
TMP_DIR=''
TMP_BASE="${TMPDIR:-/tmp}"
while [[ "$TMP_BASE" == */ ]]; do
  TMP_BASE="${TMP_BASE%/}"
done
if [[ -z "$TMP_BASE" ]]; then
  TMP_BASE='/tmp'
fi
COMPOSE=()
SUMMARY=()
NEXT_STEPS=()
FAILURES=()

# --- Colors (TTY only, NO_COLOR respected) ---------------------------------

if [[ -t 1 && -z "${NO_COLOR:-}" && "${TERM:-dumb}" != 'dumb' ]]; then
  C_RESET=$'\033[0m'
  C_BOLD=$'\033[1m'
  C_RED=$'\033[31m'
  C_GREEN=$'\033[32m'
  C_YELLOW=$'\033[33m'
  C_BLUE=$'\033[34m'
else
  C_RESET=''
  C_BOLD=''
  C_RED=''
  C_GREEN=''
  C_YELLOW=''
  C_BLUE=''
fi

# --- Output helpers --------------------------------------------------------

info() { printf '%s\n' "$*"; }

ok() { printf '%s%s%s\n' "$C_GREEN" "ok: $*" "$C_RESET"; }

warn() { printf '%s%s%s\n' "$C_YELLOW" "warning: $*" "$C_RESET" >&2; }

step() { printf '\n%s==> %s%s\n' "$C_BOLD$C_BLUE" "$*" "$C_RESET"; }

die() {
  printf '%s%s%s\n' "$C_RED" "error: $*" "$C_RESET" >&2
  exit 1
}

add_note() { SUMMARY+=("$*"); }

add_next() { NEXT_STEPS+=("$*"); }

# --- Interaction helpers ---------------------------------------------------

trim() {
  local s="$1"
  s="${s#"${s%%[![:space:]]*}"}"
  s="${s%"${s##*[![:space:]]}"}"
  printf '%s' "$s"
}

# prompt VAR "label" [default] -- sets VAR; silent when non-interactive.
prompt() {
  local var_name="$1"
  local label="$2"
  local default_value="${3:-}"
  local answer=''
  if [[ "$ASSUME_YES" -eq 1 || "$INTERACTIVE" -eq 0 ]]; then
    printf -v "$var_name" '%s' "$default_value"
    return 0
  fi
  if [[ -n "$default_value" ]]; then
    printf '%s [%s]: ' "$label" "$default_value" >&2
  else
    printf '%s: ' "$label" >&2
  fi
  if [[ -r /dev/tty ]]; then
    IFS= read -r answer < /dev/tty || answer=''
  else
    IFS= read -r answer || answer=''
  fi
  if [[ -z "$answer" ]]; then
    answer="$default_value"
  fi
  printf -v "$var_name" '%s' "$answer"
}

# Readline filename completion, with editable default and literal paths.
# Output names must not start with _path_. No eval: paths are data.
prompt_path() {
  local _path_var="$1" _path_label="$2" _path_default="${3:-}" _path_value=''
  if [[ "$ASSUME_YES" -eq 1 || "$INTERACTIVE" -eq 0 ]]; then
    printf -v "$_path_var" '%s' "$_path_default"
    return 0
  fi
  printf '%s (Tab completes paths; clear to skip): ' "$_path_label" >&2
  # Readline quotes completed names (e.g. Films\ Archive). Let read consume
  # those escapes. Quote the initial text too, so defaults round-trip.
  _path_default="${_path_default//\\/\\\\}"
  # shellcheck disable=SC2162 # intentional: undo Readline's filename quoting
  IFS= read -e -i "$_path_default" _path_value < /dev/tty || return 1
  printf -v "$_path_var" '%s' "$_path_value"
}

# confirm "question" [y|n] -- default is n.
confirm() {
  local question="$1"
  local default_answer="${2:-n}"
  local answer=''
  local suffix='[y/N]'
  if [[ "$default_answer" == 'y' ]]; then
    suffix='[Y/n]'
  fi
  if [[ "$ASSUME_YES" -eq 1 || "$INTERACTIVE" -eq 0 ]]; then
    if [[ "$default_answer" == 'y' ]]; then
      return 0
    fi
    return 1
  fi
  printf '%s %s ' "$question" "$suffix" >&2
  if [[ -r /dev/tty ]]; then
    IFS= read -r answer < /dev/tty || answer=''
  else
    IFS= read -r answer || answer=''
  fi
  case "$answer" in
    [yY]*) return 0 ;;
    [nN]*) return 1 ;;
    *)
      if [[ "$default_answer" == 'y' ]]; then
        return 0
      fi
      return 1
      ;;
  esac
}

# --- Path helpers ----------------------------------------------------------

abspath() {
  local p="$1"
  if [[ -z "$p" ]]; then
    die "empty path given"
  fi
  case "$p" in
    '~') p="$HOME" ;;
    '~'/*) p="${HOME}/${p#~/}" ;;
    '~'*) die "'~user' paths are not supported: $p" ;;
  esac
  case "$p" in
    /*) ;;
    *) p="${PWD}/${p}" ;;
  esac
  if command -v realpath >/dev/null 2>&1; then
    realpath -m -- "$p" || printf '%s' "$p"
  else
    printf '%s' "$p"
  fi
}

normalize_paths() {
  INSTALL_DIR="$(abspath "$INSTALL_DIR")"
  DATA_DIR="$(abspath "$DATA_DIR")"
  COMPOSE_DIR="$(abspath "$COMPOSE_DIR")"
  if ((${#MEDIA_DIRS[@]} > 0)); then
    local -a normalized=()
    local m=''
    for m in "${MEDIA_DIRS[@]}"; do
      normalized+=("$(abspath "$m")")
    done
    MEDIA_DIRS=("${normalized[@]}")
  fi
}

ensure_tmp() {
  if [[ -z "$TMP_DIR" ]]; then
    TMP_DIR="$(mktemp -d "${TMP_BASE}/lain-install.XXXXXX")" || die "could not create a temp directory under ${TMP_BASE}"
  fi
}

cleanup() {
  if [[ -n "$TMP_DIR" && -d "$TMP_DIR" ]]; then
    case "$TMP_DIR" in
      "${TMP_BASE}"/lain-install.*)
        rm -rf -- "$TMP_DIR" || true
        ;;
    esac
  fi
}

# --- Validation helpers ----------------------------------------------------

normalize_tag() {
  local v="$1"
  if [[ "$v" == 'latest' || -z "$v" ]]; then
    printf 'latest'
    return 0
  fi
  if [[ "$v" =~ ^v?[0-9]+\.[0-9]+\.[0-9]+([-+][0-9A-Za-z.-]+)?$ ]]; then
    printf 'v%s' "${v#v}"
    return 0
  fi
  return 1
}

validate_version() {
  local tag=''
  if ! tag="$(normalize_tag "$VERSION")"; then
    die "invalid version '$VERSION' (expected latest, v0.1.0 or 0.1.0)"
  fi
  VERSION="$tag"
}

validate_port() {
  if [[ ! "$PORT" =~ ^[0-9]{1,5}$ ]]; then
    die "invalid port '$PORT' (expected an integer between 1 and 65535)"
  fi
  if ((10#$PORT < 1 || 10#$PORT > 65535)); then
    die "invalid port '$PORT' (expected an integer between 1 and 65535)"
  fi
}

prompt_port() {
  local value=''
  while true; do
    prompt value 'HTTP port' "$PORT"
    if [[ "$value" =~ ^[0-9]{1,5}$ ]] && ((10#$value >= 1 && 10#$value <= 65535)); then
      PORT="$value"
      return 0
    fi
    warn "port must be an integer between 1 and 65535"
    if [[ "$INTERACTIVE" -eq 0 ]]; then
      die "invalid port '$value'"
    fi
  done
}

# --- Platform helpers ------------------------------------------------------

detect_arch() {
  case "$(uname -m)" in
    x86_64|amd64) printf 'x86_64' ;;
    aarch64|arm64) printf 'aarch64' ;;
    *) return 1 ;;
  esac
}

server_arch() {
  local arch=''
  if ! arch="$(detect_arch)"; then
    return 1
  fi
  case "$arch" in
    x86_64) printf 'amd64' ;;
    aarch64) printf 'arm64' ;;
    *) return 1 ;;
  esac
}

detect_distro() {
  local id='' like=''
  if [[ -r /etc/os-release ]]; then
    id="$(awk -F= '$1 == "ID" {gsub(/"/, "", $2); print $2; exit}' /etc/os-release 2>/dev/null || true)"
    like="$(awk -F= '$1 == "ID_LIKE" {gsub(/"/, "", $2); print $2; exit}' /etc/os-release 2>/dev/null || true)"
  fi
  case "$id" in
    arch|manjaro|endeavouros|garuda) printf 'arch' ;;
    debian|ubuntu|linuxmint|pop|zorin|kali) printf 'debian' ;;
    fedora|rhel|centos|rocky|almalinux) printf 'fedora' ;;
    *)
      case " $like " in
        *' arch '*) printf 'arch' ;;
        *' debian '*|*' ubuntu '*) printf 'debian' ;;
        *' fedora '*|*' rhel '*) printf 'fedora' ;;
        *) printf 'unknown' ;;
      esac
      ;;
  esac
}

desktop_deps_command() {
  case "$(detect_distro)" in
    arch)
      printf '%s' 'sudo pacman -S --needed base-devel cmake ninja qt6-base qt6-declarative mpv ffmpeg'
      ;;
    debian)
      printf '%s' 'sudo apt install build-essential cmake ninja-build qt6-base-dev qt6-declarative-dev qml6-module-qtquick qml6-module-qtquick-controls qml6-module-qtquick-layouts libmpv-dev ffmpeg'
      ;;
    fedora)
      printf '%s' 'sudo dnf install cmake ninja-build qt6-qtbase-devel qt6-qtdeclarative-devel mpv-libs-devel ffmpeg'
      ;;
    *)
      return 1
      ;;
  esac
}

run_deps_command() {
  local cmd="$1"
  local -a argv=()
  if [[ -z "$cmd" ]]; then
    return 1
  fi
  read -r -a argv <<< "$cmd"
  if ((${#argv[@]} == 0)); then
    return 1
  fi
  if [[ "$EUID" -eq 0 ]]; then
    if [[ "${argv[0]}" == 'sudo' ]]; then
      argv=("${argv[@]:1}")
    fi
  else
    if [[ "${argv[0]}" != 'sudo' ]]; then
      argv=('sudo' "${argv[@]}")
    fi
    if [[ "$INTERACTIVE" -eq 0 ]]; then
      argv=("${argv[0]}" '-n' "${argv[@]:1}")
    fi
  fi
  if [[ "$ASSUME_YES" -eq 1 || "$INTERACTIVE" -eq 0 ]]; then
    case " ${argv[*]} " in
      *' apt '*) argv+=('-y') ;;
      *' pacman '*) argv+=('--noconfirm') ;;
      *' dnf '*) argv+=('-y') ;;
    esac
  fi
  "${argv[@]}"
}

systemd_home_path() {
  local p="$1"
  if [[ "$p" == "$HOME" ]]; then
    printf '%%h'
  elif [[ "$p" == "$HOME"/* ]]; then
    printf '%%h/%s' "${p#"$HOME"/}"
  else
    printf '%s' "$p"
  fi
}

systemd_quote_arg() {
  local s=''
  s="$(systemd_home_path "$1")"
  if [[ "$s" == *[[:space:]]* ]]; then
    printf '"%s"' "${s//\"/\\\"}"
  else
    printf '%s' "$s"
  fi
}

# --- Release helpers -------------------------------------------------------

latest_tag() {
  local repo="$1"
  local effective=''
  effective="$(curl -fsSIL --proto '=https' --connect-timeout 15 -o /dev/null -w '%{url_effective}' "${GITHUB}/${repo}/releases/latest" 2>/dev/null || true)"
  case "$effective" in
    */releases/tag/*) printf '%s' "${effective##*/}" ;;
    *) return 1 ;;
  esac
}

# Numeric version used in asset names (no leading v), resolving "latest".
asset_version_for() {
  local repo="$1"
  local tag=''
  if [[ "$VERSION" == 'latest' ]]; then
    if ! tag="$(latest_tag "$repo")"; then
      return 1
    fi
  else
    tag="$VERSION"
  fi
  printf '%s' "${tag#v}"
}

release_url() {
  local repo="$1"
  local asset="$2"
  if [[ "$VERSION" == 'latest' ]]; then
    printf '%s/%s/releases/latest/download/%s' "$GITHUB" "$repo" "$asset"
  else
    printf '%s/%s/releases/download/%s/%s' "$GITHUB" "$repo" "$VERSION" "$asset"
  fi
}

download() {
  local url="$1"
  local dest="$2"
  curl -fsSL --proto '=https' --retry 3 --connect-timeout 15 --max-time 900 -o "$dest" "$url"
}

verify_checksum() {
  local file="$1"
  local sidecar="$2"
  local expected='' actual=''
  expected="$(awk 'NR == 1 {print $1}' "$sidecar")"
  if [[ ! "$expected" =~ ^[0-9a-fA-F]{64}$ ]]; then
    warn "unrecognized checksum file: $sidecar"
    return 1
  fi
  actual="$(sha256sum -- "$file" | awk '{print $1}')"
  if [[ "${expected,,}" != "${actual,,}" ]]; then
    warn "checksum mismatch for $(basename -- "$file")"
    return 1
  fi
  ok "checksum verified: $(basename -- "$file")"
  return 0
}

# fetch_release_asset URL DEST
#   0 = downloaded (checksum verified when a sidecar exists)
#   1 = download failed (missing asset / network)
#   2 = checksum verification failed
fetch_release_asset() {
  local url="$1"
  local dest="$2"
  local sidecar="${dest}.sha256"
  if ! download "$url" "$dest"; then
    return 1
  fi
  if download "${url}.sha256" "$sidecar" 2>/dev/null; then
    if verify_checksum "$dest" "$sidecar"; then
      return 0
    fi
    return 2
  fi
  warn "no .sha256 sidecar for $(basename -- "$url"); skipping checksum verification"
  return 0
}

# --- Compose helpers -------------------------------------------------------

detect_compose() {
  COMPOSE=()
  if command -v docker >/dev/null 2>&1; then
    if docker compose version >/dev/null 2>&1; then
      COMPOSE=(docker compose)
      return 0
    fi
  fi
  if command -v docker-compose >/dev/null 2>&1; then
    COMPOSE=(docker-compose)
    return 0
  fi
  return 1
}

docker_ready() {
  if ((${#COMPOSE[@]} == 0)); then
    return 1
  fi
  docker info >/dev/null 2>&1
}

compose_run() {
  if ((${#COMPOSE[@]} == 0)); then
    return 1
  fi
  (cd "$COMPOSE_DIR" && "${COMPOSE[@]}" "$@")
}

yaml_quote() {
  local s="$1"
  s="${s//\\/\\\\}"
  s="${s//\"/\\\"}"
  printf '"%s"' "$s"
}

sanitize_name() {
  local base='' name=''
  base="$(basename -- "$1")"
  name="$(printf '%s' "$base" | tr '[:upper:]' '[:lower:]' | sed -e 's/[^a-z0-9._-]/-/g' -e 's/--*/-/g' -e 's/^[-._]*//' -e 's/[-._]*$//')"
  if [[ -z "$name" || "$name" == '.' || "$name" == '..' ]]; then
    name='media'
  fi
  printf '%s' "$name"
}

# Short-syntax bind mounts cannot express a host path containing ':' or a
# newline; fail early with a clear message instead of writing broken YAML.
check_docker_path() {
  local path="$1"
  local label="$2"
  if [[ "$path" == *$'\n'* ]]; then
    warn "$label contains a newline and cannot be used as a Docker bind mount: $path"
    return 1
  fi
  if [[ "$path" == *:* ]]; then
    warn "$label contains ':' and cannot be used as a Docker bind mount: $path"
    return 1
  fi
  return 0
}

write_compose_file() {
  local image="$1"
  shift
  local compose_file="${COMPOSE_DIR}/docker-compose.yml"
  local tmp="${compose_file}.tmp.$$"
  local backup=''
  local volume=''
  if [[ -f "$compose_file" ]]; then
    backup="${compose_file}.bak.$(date +%Y%m%d%H%M%S).$$"
    if cp -a -- "$compose_file" "$backup"; then
      warn "existing compose file backed up to $backup"
    else
      warn "could not back up $compose_file"
      return 1
    fi
  fi
  {
    printf '# %s -- yours to audit and edit.\n' "$GENERATED_MARKER"
    printf '# Apply edits: docker compose up -d\n'
    printf '# Volume syntax: HOST_DIRECTORY:CONTAINER_DIRECTORY:ro\n'
    printf '# Add media mounts below, then register their CONTAINER paths in Lain.\n'
    printf '# Example: /srv/media/films:/media/films:ro\n'
    printf '# Re-running the installer reuses this file by default.\n'
    printf 'services:\n'
    printf '  lain:\n'
    printf '    image: %s\n' "$image"
    printf '    container_name: lain\n'
    printf '    restart: unless-stopped\n'
    # shellcheck disable=SC2016  # literal ${UID}:${GID}; values come from .env
    printf '    user: "${UID}:${GID}"\n'
    printf '    ports:\n'
    printf '      - "%s:%s"\n' "$PORT" "$CONTAINER_PORT"
    printf '    volumes:\n'
    printf '      # Persistent database and cache (read/write).\n'
    printf '      - %s\n' "$(yaml_quote "${DATA_DIR}:${CONTAINER_DATA_DIR}")"
    printf '      # Media stays on the host; mount read-only.\n'
    for volume in "$@"; do
      printf '      - %s\n' "$(yaml_quote "$volume")"
    done
    printf '    environment:\n'
    printf '      GOMEMLIMIT: 256MiB\n'
    printf '      GOGC: "100"\n'
    printf '    mem_limit: 384m\n'
    printf '    healthcheck:\n'
    printf '      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:%s/health"]\n' "$CONTAINER_PORT"
    printf '      interval: 30s\n'
    printf '      timeout: 5s\n'
    printf '      start_period: 5s\n'
    printf '      retries: 3\n'
  } > "$tmp" || {
    rm -f -- "$tmp" || true
    return 1
  }
  if ! mv -f -- "$tmp" "$compose_file"; then
    rm -f -- "$tmp" || true
    return 1
  fi
  ok "Wrote $compose_file"
  return 0
}

write_env_file() {
  local env_file="${COMPOSE_DIR}/.env"
  local tmp="${env_file}.tmp.$$"
  local backup=''
  if [[ -f "$env_file" ]]; then
    backup="${env_file}.bak.$(date +%Y%m%d%H%M%S).$$"
    if cp -a -- "$env_file" "$backup"; then
      warn "existing .env backed up to $backup"
    else
      warn "could not back up $env_file"
      return 1
    fi
  fi
  {
    printf '# %s -- host UID/GID; edit to match the media owner.\n' "$GENERATED_MARKER"
    printf 'UID=%s\n' "$(id -u)"
    printf 'GID=%s\n' "$(id -g)"
  } > "$tmp" || {
    rm -f -- "$tmp" || true
    return 1
  }
  if ! mv -f -- "$tmp" "$env_file"; then
    rm -f -- "$tmp" || true
    return 1
  fi
  ok "Wrote $env_file (UID/GID for the container user)"
  return 0
}

print_compose_manual() {
  info "Start it manually with:"
  info "  cd ${COMPOSE_DIR} && docker compose pull && docker compose up -d"
  info "  docker compose logs -f"
}

check_path() {
  case ":${PATH}:" in
    *":${INSTALL_DIR}:"*) ;;
    *) warn "${INSTALL_DIR} is not in your PATH; add it to your shell profile, e.g. export PATH=\"\$PATH:${INSTALL_DIR}\"" ;;
  esac
}

# --- Server: Docker --------------------------------------------------------

install_server_docker() {
  local image="${DOCKER_IMAGE}:${VERSION}"
  local -a targets=()
  local -A used_names=()
  local dir='' name='' final='' used=0
  step "Server via Docker (${image})"
  if [[ "$REUSE_COMPOSE" -eq 0 ]]; then
    if ! check_docker_path "$DATA_DIR" 'data directory'; then
      return 1
    fi
    if ! mkdir -p -- "$DATA_DIR" "$COMPOSE_DIR"; then
      warn "could not create ${DATA_DIR} or ${COMPOSE_DIR}"
      return 1
    fi
    for dir in "${MEDIA_DIRS[@]}"; do
      if ! check_docker_path "$dir" 'media directory'; then
        continue
      fi
      if [[ ! -d "$dir" ]]; then
        warn "media directory does not exist: $dir"
        if confirm "Create it?" y; then
          if ! mkdir -p -- "$dir"; then
            warn "could not create $dir; skipping it"
            continue
          fi
        else
          warn "skipping $dir"
          continue
        fi
      fi
      name="$(sanitize_name "$dir")"
      final="$name"
      used=1
      while [[ -n "${used_names[$final]:-}" ]]; do
        used=$((used + 1))
        final="${name}-${used}"
      done
      used_names["$final"]=1
      targets+=("${dir}:/media/${final}:ro")
    done
    if ! write_compose_file "$image" "${targets[@]}"; then
      warn "could not write ${COMPOSE_DIR}/docker-compose.yml"
      return 1
    fi
    if ! write_env_file; then
      warn "could not write ${COMPOSE_DIR}/.env"
      return 1
    fi
  else
    ok "Reusing ${COMPOSE_DIR}/docker-compose.yml (manual edits preserved)"
    if [[ ! -f "${COMPOSE_DIR}/.env" ]] && ! write_env_file; then
      warn "could not create ${COMPOSE_DIR}/.env"
      return 1
    fi
  fi
  add_note "server (Docker): ${image}"
  add_note "compose file: ${COMPOSE_DIR}/docker-compose.yml"
  add_note "data directory: ${DATA_DIR}"
  for dir in "${targets[@]}"; do
    add_note "media (read-only): $dir"
  done
  add_next "Open http://127.0.0.1:${PORT}/ and create the admin account"
  add_next "Register libraries using container paths such as /media/videos"
  add_next "Edit ${COMPOSE_DIR}/docker-compose.yml to add volumes; apply with docker compose up -d from that directory"
  info "Compose file (host paths on the left, container paths on the right):"
  cat -- "${COMPOSE_DIR}/docker-compose.yml"
  if docker_ready; then
    if confirm "Is this Compose file ready to validate and apply?" y; then
      if ! compose_run config --quiet; then
        warn "invalid Compose configuration; review ${COMPOSE_DIR}/docker-compose.yml"
        return 1
      elif ! compose_run pull; then
        warn "docker compose pull failed"
        print_compose_manual
      elif ! compose_run up -d; then
        warn "docker compose up -d failed"
        print_compose_manual
      else
        ok "Container started: http://127.0.0.1:${PORT}/"
        offer_terminal_wizard || warn "Terminal setup incomplete; continue in the web UI or re-run the installer"
      fi
    else
      print_compose_manual
    fi
  else
    warn "Docker is not available or the daemon is not running; wrote the compose file only"
    print_compose_manual
  fi
  return 0
}

# --- Optional terminal setup (Docker) --------------------------------------

# Values reach jq/curl over stdin, never in process arguments or Compose.
json_object() {
  printf '%s\0' "$@" | jq -Rs '
    split("\u0000")[:-1] as $v |
    reduce range(0; $v|length; 2) as $i ({}; .[$v[$i]] = $v[$i+1])'
}

wizard_request() {
  local method="$1" route="$2" payload="${3:-}"
  WIZARD_REPLY=''
  WIZARD_STATUS=''
  ensure_tmp
  # The authorization header is delivered through a pipe-backed descriptor.
  WIZARD_STATUS="$(printf '%s' "$payload" | curl --silent --show-error \
    --connect-timeout 2 --max-time 15 --noproxy '*' \
    --request "$method" --header 'Content-Type: application/json' \
    --header @<(if [[ -n "${WIZARD_TOKEN:-}" ]]; then printf 'Authorization: Bearer %s\n' "$WIZARD_TOKEN"; fi) \
    --data-binary @- --output "${TMP_DIR}/wizard-response" --write-out '%{http_code}' \
    "${WIZARD_URL}${route}")" || return 1
  WIZARD_REPLY="$(cat "${TMP_DIR}/wizard-response")"
  rm -f -- "${TMP_DIR}/wizard-response"
  [[ "$WIZARD_STATUS" == 2?? ]]
}

wizard_error() {
  local message=''
  message="$(printf '%s' "$WIZARD_REPLY" | jq -r '.error // "Request failed"' 2>/dev/null)" || message='Invalid server response'
  warn "HTTP ${WIZARD_STATUS:-unavailable}: $message"
}

prompt_password() {
  local _secret=''
  printf '%s: ' "$2" >&2
  if ! IFS= read -r -s _secret < /dev/tty; then
    printf '\n' >&2
    return 1
  fi
  printf '\n' >&2
  printf -v "$1" '%s' "$_secret"
}

# Longest matching mount wins; /films must not match /films-other.
container_path() {
  local host="$1" best='' target='' i root
  for i in "${!WIZARD_HOSTS[@]}"; do
    root="${WIZARD_HOSTS[$i]%/}"
    if [[ "$host" == "$root" || "$host" == "$root/"* ]]; then
      if [[ -z "$target" || ${#root} -gt ${#best} ]]; then
        best="$root"
        target="${WIZARD_PATHS[$i]%/}${host#"$root"}"
      fi
    fi
  done
  [[ -n "$target" ]] || return 1
  printf '%s\n' "$target"
}

terminal_wizard() {
  local WIZARD_TOKEN='' WIZARD_REPLY='' WIZARD_STATUS=''
  local username='' password='' repeated='' credentials='' needs_setup=''
  local host='' path='' name='' kind='' libraries='' attempt
  step 'Terminal setup'
  for ((attempt=0; attempt<30; attempt++)); do
    if wizard_request GET /api/setup/status; then break; fi
    sleep 1
  done
  if [[ "$WIZARD_STATUS" != 200 ]]; then
    warn "Server not ready at ${WIZARD_URL}; finish setup in the browser later"
    return 1
  fi
  needs_setup="$(printf '%s' "$WIZARD_REPLY" | jq -er '.setup_required | tostring')" || return 1
  [[ "$needs_setup" == true || "$needs_setup" == false ]] || return 1
  if [[ "$needs_setup" == true ]]; then
    info 'Create the first administrator account.'
  else
    info 'Server already configured. Sign in as an administrator to add libraries.'
  fi
  while true; do
    prompt username 'Admin username' admin
    prompt_password password 'Password' || return 1
    if [[ "$needs_setup" == true ]]; then
      prompt_password repeated 'Repeat password' || return 1
      if [[ "$password" != "$repeated" ]]; then
        warn 'Passwords do not match'
        continue
      fi
    fi
    credentials="$(json_object username "$username" password "$password")" || return 1
    password=''; repeated=''
    if [[ "$needs_setup" == true ]]; then
      if ! wizard_request POST /api/setup "$credentials"; then
        credentials=''
        wizard_error
        confirm 'Retry account setup?' y || return 1
        # Account creation may have succeeded before a connection failure.
        wizard_request GET /api/setup/status || return 1
        needs_setup="$(printf '%s' "$WIZARD_REPLY" | jq -er '.setup_required | tostring')" || return 1
        continue
      fi
      needs_setup=false
    fi
    if wizard_request POST /api/auth/login "$credentials"; then
      credentials=''
      WIZARD_TOKEN="$(printf '%s' "$WIZARD_REPLY" | jq -er '.token | select(type == "string" and length > 0)')" || return 1
      break
    fi
    credentials=''
    wizard_error
    confirm 'Retry login?' y || return 1
  done
  wizard_request GET /api/me || return 1
  if ! printf '%s' "$WIZARD_REPLY" | jq -e '.role == "admin"' >/dev/null; then
    warn 'An administrator account is required to register libraries'
    return 1
  fi
  info 'Choose library folders on the host; their mounted container paths are sent to Lain.'
  for attempt in "${!WIZARD_HOSTS[@]}"; do
    info "  ${WIZARD_HOSTS[$attempt]} -> ${WIZARD_PATHS[$attempt]}"
  done
  while ((${#WIZARD_HOSTS[@]} > 0)) && confirm 'Register a library now?' y; do
    prompt_path host 'Library directory (a mounted folder or subfolder)' "${WIZARD_HOSTS[0]}" || return 1
    [[ -n "$host" ]] || break
    host="$(abspath "$host")"
    if [[ ! -d "$host" ]] || ! path="$(container_path "$host")"; then
      warn 'Choose an existing directory inside a listed mount. To use another root, add its volume to Compose and re-run.'
      continue
    fi
    wizard_request GET /api/libraries || { wizard_error; return 1; }
    libraries="$WIZARD_REPLY"
    if printf '%s' "$libraries" | jq -e --arg path "$path" 'any(.[]; .path == $path)' >/dev/null; then
      info "Already registered: $path"
      continue
    fi
    prompt name 'Library name' "$(basename "$host")"
    while true; do
      prompt kind 'Library type (anime / movie / series)' anime
      case "$kind" in anime|movie|series) break ;; *) warn 'Choose anime, movie or series' ;; esac
    done
    info "Registering ${name}: ${host} -> ${path} (${kind})"
    if wizard_request POST /api/libraries "$(json_object name "$name" type "$kind" path "$path")"; then
      ok "Library registered: $name"
    else
      wizard_error
    fi
  done
  if ((${#WIZARD_HOSTS[@]} == 0)); then
    info 'No media bind mounts found. Add them to Compose and re-run, or register container paths in the web UI.'
  fi
  if confirm 'Start a library scan now?' y; then
    if wizard_request POST /api/library/scan; then
      ok 'Scan started; follow its progress in the web UI'
    elif [[ "$WIZARD_STATUS" == 409 ]]; then
      info 'A scan is already running'
    else
      wizard_error
      return 1
    fi
  fi
  add_note "Terminal setup finished: ${WIZARD_URL}/"
}

offer_terminal_wizard() {
  [[ "$INTERACTIVE" -eq 1 && "$ASSUME_YES" -eq 0 ]] || return 0
  confirm 'Run the setup wizard here (admin account, libraries and scan)?' y || return 0
  if ! command -v jq >/dev/null 2>&1 || ! command -v curl >/dev/null 2>&1; then
    warn 'The optional terminal wizard needs curl and jq. You can use the web UI instead.'
    return 0
  fi
  local binding='' mounts='' entry=''
  local WIZARD_URL=''
  local -a WIZARD_HOSTS=() WIZARD_PATHS=()
  binding="$(compose_run port lain "$CONTAINER_PORT")" || return 1
  binding="${binding%%$'\n'*}"
  [[ "${binding##*:}" =~ ^[0-9]+$ ]] || return 1
  WIZARD_URL="http://127.0.0.1:${binding##*:}"
  mounts="$(docker inspect lain --format '{{json .Mounts}}')" || return 1
  # Read actual mounts, including manually edited Compose volumes.
  printf '%s' "$mounts" | jq -e 'type == "array"' >/dev/null || return 1
  while IFS= read -r entry; do
    WIZARD_HOSTS+=("$(printf '%s' "$entry" | jq -r '.Source')")
    WIZARD_PATHS+=("$(printf '%s' "$entry" | jq -r '.Destination')")
  done < <(printf '%s' "$mounts" | jq -c '.[] | select(.Type == "bind" and .Destination != "/data")')
  terminal_wizard
}

# --- Server: binary / daemon -----------------------------------------------

install_server_binary() {
  local arch='' ver='' asset='' url='' archive='' extract='' bin=''
  local rc=0
  ensure_tmp
  if ! arch="$(server_arch)"; then
    warn "unsupported CPU architecture: $(uname -m) (server builds exist for x86_64 and aarch64)"
    return 1
  fi
  if ! ver="$(asset_version_for "$SERVER_REPO")"; then
    warn "could not determine the latest server release tag (network problem?)"
    warn "pin a release explicitly, e.g. --version v0.1.0"
    return 1
  fi
  asset="lain_${ver}_linux_${arch}.tar.gz"
  url="$(release_url "$SERVER_REPO" "$asset")"
  archive="${TMP_DIR}/${asset}"
  extract="${TMP_DIR}/server"
  if ! mkdir -p -- "$extract"; then
    warn "could not create $extract"
    return 1
  fi
  step "Server binary ${VERSION} (${arch})"
  info "Downloading ${url}"
  fetch_release_asset "$url" "$archive" || rc=$?
  if [[ "$rc" -eq 1 ]]; then
    warn "release asset not found: $url"
    warn "see available releases: ${GITHUB}/${SERVER_REPO}/releases"
    return 1
  fi
  if [[ "$rc" -ne 0 ]]; then
    warn "checksum verification failed for $url"
    return 1
  fi
  if ! tar -xzf "$archive" -C "$extract"; then
    warn "could not extract $archive"
    return 1
  fi
  bin="$(find "$extract" -maxdepth 2 -type f -name 'lain' -print -quit)"
  if [[ -z "$bin" ]]; then
    warn "'lain' binary not found inside $asset"
    return 1
  fi
  if ! mkdir -p -- "$INSTALL_DIR"; then
    warn "could not create $INSTALL_DIR"
    return 1
  fi
  if ! install -m 0755 "$bin" "${INSTALL_DIR}/lain"; then
    warn "could not install ${INSTALL_DIR}/lain"
    return 1
  fi
  ok "Installed ${INSTALL_DIR}/lain"
  check_path
  add_note "server CLI: ${INSTALL_DIR}/lain"
  add_next "Run: \"${INSTALL_DIR}/lain\" serve --data-dir \"${DATA_DIR}\" --port ${PORT}"
  add_next "Open http://127.0.0.1:${PORT}/ for first-run setup"
  return 0
}

print_systemd_manual() {
  info "Control it manually with:"
  info "  systemctl --user daemon-reload"
  info "  systemctl --user enable --now lain.service"
  info "  systemctl --user status lain.service"
}

enable_linger_if_wanted() {
  local user="${USER:-$(id -un)}"
  local linger=''
  linger="$(loginctl show-user "$user" -p Linger --value 2>/dev/null || true)"
  if [[ "$linger" == 'yes' ]]; then
    return 0
  fi
  info "Tip: a user service stops when you log out unless lingering is enabled."
  if confirm "Run 'loginctl enable-linger' so lain keeps running after logout?" n; then
    if loginctl enable-linger "$user"; then
      ok "enabled lingering for $user"
    else
      warn "loginctl enable-linger failed; run it manually: loginctl enable-linger $user"
    fi
  else
    info "Keep it running after logout later with: loginctl enable-linger $user"
  fi
  return 0
}

install_systemd_unit() {
  local unit_dir="${HOME}/.config/systemd/user"
  local unit_file="${unit_dir}/lain.service"
  local tmp="${unit_file}.tmp.$$"
  local exe='' data=''
  if ! command -v systemctl >/dev/null 2>&1; then
    warn "systemctl not found; skipping the systemd user service"
    return 1
  fi
  if ! confirm "Create and start the lain systemd user service?" y; then
    info "Skipped; create it later by re-running: ${SCRIPT_PATH:-install.sh} --server --server-mode daemon"
    return 0
  fi
  exe="$(systemd_quote_arg "${INSTALL_DIR}/lain")"
  data="$(systemd_quote_arg "$DATA_DIR")"
  if ! mkdir -p -- "$unit_dir"; then
    warn "could not create $unit_dir"
    return 1
  fi
  {
    printf '# %s -- do not edit; re-run the installer to regenerate.\n' "$GENERATED_MARKER"
    printf '[Unit]\n'
    printf 'Description=lain media server\n'
    printf 'Documentation=%s/%s\n' "$GITHUB" "$SERVER_REPO"
    printf '\n[Service]\n'
    printf 'ExecStart=%s serve --data-dir %s --port %s\n' "$exe" "$data" "$PORT"
    printf 'Restart=on-failure\n'
    printf 'RestartSec=3\n'
    printf '\n[Install]\n'
    printf 'WantedBy=default.target\n'
  } > "$tmp" || {
    rm -f -- "$tmp" || true
    warn "could not write $unit_file"
    return 1
  }
  if ! mv -f -- "$tmp" "$unit_file"; then
    rm -f -- "$tmp" || true
    warn "could not write $unit_file"
    return 1
  fi
  ok "Wrote $unit_file"
  if ! systemctl --user daemon-reload; then
    warn "systemctl --user daemon-reload failed"
    print_systemd_manual
    return 1
  fi
  if systemctl --user enable --now lain.service; then
    ok "systemd user service enabled and started"
    add_note "user service: $unit_file"
    add_next "systemctl --user status lain.service"
    add_next "journalctl --user -u lain.service -f"
  else
    warn "could not enable/start the user service"
    print_systemd_manual
    return 1
  fi
  enable_linger_if_wanted
  return 0
}

install_server_daemon() {
  if ! install_server_binary; then
    return 1
  fi
  if ! install_systemd_unit; then
    warn "the server binary is installed but the user service is not active"
    return 1
  fi
  return 0
}

# --- Desktop ---------------------------------------------------------------

warn_if_missing_libs() {
  local bin="$1"
  local missing='' deps=''
  if ! command -v ldd >/dev/null 2>&1; then
    return 0
  fi
  missing="$(ldd "$bin" 2>/dev/null | grep 'not found' || true)"
  if [[ -z "$missing" ]]; then
    return 0
  fi
  warn "some shared libraries are missing for $bin:"
  printf '%s\n' "$missing" >&2
  if deps="$(desktop_deps_command)"; then
    info "Install them with: $deps"
  fi
  return 0
}

install_desktop_binary() {
  local bin="$1"
  local kind="${2:-binary}"
  local icon_source="${3:-}"
  local app_dir="${HOME}/.local/share/applications"
  local icon_dir="${HOME}/.local/share/icons/hicolor/256x256/apps"
  local icon_file="${icon_dir}/lain-desktop.png"
  local desktop_file="${app_dir}/lain-desktop.desktop"
  local extract_dir=''
  local tmp="${desktop_file}.tmp.$$"
  if ! mkdir -p -- "$INSTALL_DIR"; then
    warn "could not create $INSTALL_DIR"
    return 1
  fi
  if ! install -m 0755 "$bin" "${INSTALL_DIR}/lain-desktop"; then
    warn "could not install ${INSTALL_DIR}/lain-desktop"
    return 1
  fi
  ok "Installed ${INSTALL_DIR}/lain-desktop"
  check_path
  if [[ "$kind" != 'appimage' ]]; then
    warn_if_missing_libs "${INSTALL_DIR}/lain-desktop"
  fi
  if [[ -z "$icon_source" && "$kind" == 'appimage' ]]; then
    extract_dir="${TMP_DIR}/lain-desktop-icon"
    # Downloads land non-executable (curl + umask); the image must run
    # to unpack its own icon, so mark it executable first.
    if mkdir -p -- "$extract_dir" &&
       chmod +x -- "$bin" 2>/dev/null &&
       (cd "$extract_dir" && "$bin" --appimage-extract \
         'usr/share/icons/hicolor/256x256/apps/lain-desktop.png' >/dev/null 2>&1) &&
       [[ -f "${extract_dir}/squashfs-root/usr/share/icons/hicolor/256x256/apps/lain-desktop.png" ]]; then
      icon_source="${extract_dir}/squashfs-root/usr/share/icons/hicolor/256x256/apps/lain-desktop.png"
    fi
  fi
  if ! mkdir -p -- "$app_dir" "$icon_dir"; then
    warn "could not create desktop integration directories"
    return 1
  fi
  if [[ -n "$icon_source" && -f "$icon_source" ]]; then
    if ! install -m 0644 "$icon_source" "$icon_file"; then
      warn "could not install $icon_file"
      return 1
    fi
    ok "Installed $icon_file"
  else
    warn "desktop icon was not found in the installation payload"
  fi
  {
    printf '[Desktop Entry]\n'
    printf '# %s -- do not edit; re-run the installer to regenerate.\n' "$GENERATED_MARKER"
    printf 'Type=Application\n'
    printf 'Name=Lain\n'
    printf 'GenericName=Media Client\n'
    printf 'Comment=lain media server desktop client\n'
    printf 'Exec=lain-desktop\n'
    printf 'Icon=lain-desktop\n'
    printf 'Terminal=false\n'
    printf 'Categories=AudioVideo;Player;\n'
    printf 'Keywords=media;player;lain;\n'
    printf 'StartupWMClass=lain-desktop\n'
  } > "$tmp" || {
    rm -f -- "$tmp" || true
    warn "could not write $desktop_file"
    return 1
  }
  if ! mv -f -- "$tmp" "$desktop_file"; then
    rm -f -- "$tmp" || true
    warn "could not write $desktop_file"
    return 1
  fi
  ok "Wrote $desktop_file"
  if command -v update-desktop-database >/dev/null 2>&1; then
    update-desktop-database "$app_dir" || warn "update-desktop-database failed (harmless)"
  else
    info "update-desktop-database not found; the application menu may need a moment to refresh"
  fi
  add_note "desktop client: ${INSTALL_DIR}/lain-desktop"
  add_next "Launch the client with: lain-desktop (or from the application menu)"
  if [[ "$kind" == 'appimage' ]]; then
    add_next "No FUSE? Run it as: lain-desktop --appimage-extract-and-run"
  fi
  return 0
}

build_desktop_from_source() {
  local deps='' src='' build='' bin=''
  local tool=''
  step "Building lain-desktop from source"
  if deps="$(desktop_deps_command)"; then
    info "Dependencies: $deps"
    if confirm "Install distro dependencies now?" y; then
      run_deps_command "$deps" || warn "dependency install failed (continuing; the build may fail)"
    else
      warn "skipping dependency install; the build may fail"
    fi
  else
    warn "unrecognized distribution; install Qt6 (base + declarative), libmpv, cmake, ninja and git manually"
    warn "see ${GITHUB}/${DESKTOP_REPO}"
  fi
  for tool in git cmake ninja; do
    if ! command -v "$tool" >/dev/null 2>&1; then
      warn "required tool not found: $tool"
      return 1
    fi
  done
  ensure_tmp
  src="${TMP_DIR}/lain-desktop-src"
  info "Cloning ${GITHUB}/${DESKTOP_REPO}.git"
  if ! git clone --depth 1 "${GITHUB}/${DESKTOP_REPO}.git" "$src"; then
    warn "git clone failed"
    return 1
  fi
  build="${src}/build"
  if ! cmake -S "$src" -B "$build" -G Ninja -DCMAKE_BUILD_TYPE=Release; then
    warn "cmake configure failed"
    return 1
  fi
  if ! cmake --build "$build"; then
    warn "cmake build failed"
    return 1
  fi
  bin="$(find "$build" -maxdepth 3 -type f -perm -u+x \( -name 'lain-desktop' -o -name 'lain' \) -print -quit)"
  if [[ -z "$bin" ]]; then
    warn "built binary not found under $build"
    return 1
  fi
  if ! install_desktop_binary "$bin" binary "${src}/packaging/lain-desktop.png"; then
    return 1
  fi
  return 0
}

install_desktop() {
  local arch='' ver='' asset='' url='' image=''
  local rc=0
  ensure_tmp
  if ! arch="$(detect_arch)"; then
    warn "unsupported CPU architecture: $(uname -m) (desktop builds exist for x86_64)"
    return 1
  fi
  step "Desktop client (${VERSION}, ${arch})"
  if [[ "$arch" != 'x86_64' ]]; then
    warn "no prebuilt desktop AppImage is published for ${arch}; a source build is needed"
    if confirm "Build lain-desktop from source now?" y; then
      build_desktop_from_source || return 1
      return 0
    fi
    warn "skipped the desktop install"
    return 1
  fi
  if ver="$(asset_version_for "$DESKTOP_REPO")"; then
    asset="lain-desktop_${ver}_linux_x86_64.AppImage"
    url="$(release_url "$DESKTOP_REPO" "$asset")"
    image="${TMP_DIR}/${asset}"
    info "Downloading ${url}"
    fetch_release_asset "$url" "$image" || rc=$?
  else
    rc=1
  fi
  if [[ "$rc" -eq 0 ]]; then
    install_desktop_binary "$image" appimage || return 1
    return 0
  fi
  if [[ "$rc" -eq 2 ]]; then
    warn "the downloaded AppImage failed checksum verification; not installing it"
  else
    warn "no prebuilt desktop AppImage is available for this version/arch"
    if [[ -n "$url" ]]; then
      info "Requested: $url"
    fi
    warn "the desktop app can also be built from source against system Qt6 + libmpv"
  fi
  if confirm "Build lain-desktop from source now?" y; then
    build_desktop_from_source || return 1
    return 0
  fi
  warn "skipped the desktop install"
  return 1
}

# --- Interactive configuration ---------------------------------------------

choose_components() {
  local choice=''
  printf '\nWhat should be installed?\n' >&2
  printf '  1) Server only (recommended)\n' >&2
  printf '  2) Server + Desktop\n' >&2
  printf '  3) Desktop only\n' >&2
  printf '  4) Uninstall lain\n' >&2
  printf '  5) Quit\n' >&2
  while true; do
    prompt choice 'Choice' '1'
    case "$choice" in
      1) SERVER=1; DESKTOP=0; return 0 ;;
      2) SERVER=1; DESKTOP=1; return 0 ;;
      3) SERVER=0; DESKTOP=1; return 0 ;;
      4) UNINSTALL=1; return 0 ;;
      5) exit 0 ;;
      *) warn "invalid choice: $choice" ;;
    esac
    if [[ "$INTERACTIVE" -eq 0 ]]; then
      die "invalid choice '$choice' and no terminal to retry"
    fi
  done
}

choose_server_mode() {
  local choice=''
  printf '\nServer install mode:\n' >&2
  printf '  1) Docker (recommended)\n' >&2
  printf '  2) Static binary (CLI only)\n' >&2
  printf '  3) Daemon (systemd user service)\n' >&2
  while true; do
    prompt choice 'Choice' '1'
    case "$choice" in
      1) MODE='docker'; return 0 ;;
      2) MODE='binary'; return 0 ;;
      3) MODE='daemon'; return 0 ;;
      *) warn "invalid choice: $choice" ;;
    esac
    if [[ "$INTERACTIVE" -eq 0 ]]; then
      die "invalid choice '$choice' and no terminal to retry"
    fi
  done
}

parse_media_list() {
  local input="$1"
  local item=''
  local -a parts=()
  MEDIA_DIRS=()
  IFS=',' read -r -a parts <<< "$input"
  for item in "${parts[@]}"; do
    item="$(trim "$item")"
    if [[ -n "$item" ]]; then
      MEDIA_DIRS+=("$item")
    fi
  done
}

configure_server_binary() {
  if [[ "$INSTALL_SET" -eq 0 ]]; then
    prompt_path INSTALL_DIR 'Install directory' "$INSTALL_DIR"
    [[ -n "$INSTALL_DIR" ]] || die 'Install directory is required'
  fi
  if [[ "$DATA_SET" -eq 0 ]]; then
    prompt_path DATA_DIR 'Data directory' "$DATA_DIR"
    [[ -n "$DATA_DIR" ]] || die 'Data directory is required'
  fi
  if [[ "$PORT_SET" -eq 0 ]]; then
    prompt_port
  fi
  if [[ "$VERSION_SET" -eq 0 ]]; then
    prompt VERSION 'Release tag (latest, v0.1.0 or 0.1.0)' "$VERSION"
  fi
}

configure_desktop() {
  if [[ "$INSTALL_SET" -eq 0 ]]; then
    prompt_path INSTALL_DIR 'Install directory' "$INSTALL_DIR"
    [[ -n "$INSTALL_DIR" ]] || die 'Install directory is required'
  fi
  if [[ "$VERSION_SET" -eq 0 ]]; then
    prompt VERSION 'Release tag (latest, v0.1.0 or 0.1.0)' "$VERSION"
  fi
}

configure_docker() {
  local default_media=''
  local media_input=''
  local regenerate_default='n'
  if [[ "$COMPOSE_SET" -eq 0 ]]; then
    prompt_path COMPOSE_DIR 'Compose directory' "$COMPOSE_DIR"
    [[ -n "$COMPOSE_DIR" ]] || die 'Compose directory is required'
    COMPOSE_DIR="$(abspath "$COMPOSE_DIR")"
  fi
  if [[ -f "${COMPOSE_DIR}/docker-compose.yml" ]]; then
    info "Found ${COMPOSE_DIR}/docker-compose.yml (including any manual edits)."
    if grep -qF "$GENERATED_MARKER -- do not edit" "${COMPOSE_DIR}/docker-compose.yml"; then
      info 'This is a legacy generated file; regeneration upgrades it to the auditable format.'
      regenerate_default='y'
    elif [[ "$DATA_SET" -eq 1 || "$PORT_SET" -eq 1 || "$VERSION_SET" -eq 1 || "$MEDIA_GIVEN" -eq 1 ]]; then
      info 'Explicit Docker options were supplied; regeneration applies them.'
      regenerate_default='y'
    fi
    if ! confirm 'Regenerate it from installer options? Existing files will be backed up.' "$regenerate_default"; then
      REUSE_COMPOSE=1
      return 0
    fi
  fi
  if [[ "$DATA_SET" -eq 0 ]]; then
    prompt_path DATA_DIR "Data directory (mounted at ${CONTAINER_DATA_DIR})" "$DATA_DIR"
    [[ -n "$DATA_DIR" ]] || die 'Data directory is required'
  fi
  if [[ "$PORT_SET" -eq 0 ]]; then
    prompt_port
  fi
  if [[ "$VERSION_SET" -eq 0 ]]; then
    prompt VERSION 'Image tag (latest, v0.1.0 or 0.1.0)' "$VERSION"
  fi
  if [[ "$MEDIA_GIVEN" -eq 0 ]]; then
    if [[ -d "$DEFAULT_MEDIA_DIR" ]]; then
      default_media="$DEFAULT_MEDIA_DIR"
    fi
    MEDIA_DIRS=()
    while true; do
      prompt_path media_input 'Media directory on the host' "$default_media" || break
      if [[ -n "$media_input" ]]; then
        MEDIA_DIRS+=("$media_input")
      fi
      confirm 'Add another media directory?' n || break
      default_media=''
    done
  fi
}

# --- Uninstall -------------------------------------------------------------

remove_generated() {
  local file="$1"
  if [[ -z "$file" || "$file" != /* || "$file" == '/' ]]; then
    warn "refusing to remove unsafe path: '$file'"
    return 0
  fi
  if [[ ! -e "$file" ]]; then
    return 0
  fi
  if ! grep -qF "$GENERATED_MARKER" "$file" 2>/dev/null; then
    warn "refusing to remove '$file' (not created by this installer)"
    return 0
  fi
  if rm -f -- "$file"; then
    ok "Removed $file"
  else
    warn "could not remove $file"
  fi
  return 0
}

choose_uninstall_level() {
  local choice=''
  printf '\nCleanup level (media files are never touched):\n' >&2
  printf '  1) Stop only: halt the container and the user service, remove nothing\n' >&2
  printf '  2) Standard: stop everything, remove generated files and installed binaries, keep data\n' >&2
  printf '  3) Full: standard, plus erase the data directory contents\n' >&2
  while true; do
    prompt choice 'Choice' '2'
    case "$choice" in
      1) UNINSTALL_LEVEL='stop'; return 0 ;;
      2) UNINSTALL_LEVEL='standard'; return 0 ;;
      3) UNINSTALL_LEVEL='full'; return 0 ;;
      stop|standard|full) UNINSTALL_LEVEL="$choice"; return 0 ;;
      *) warn "invalid choice: $choice" ;;
    esac
    if [[ "$INTERACTIVE" -eq 0 ]]; then
      die "invalid choice '$choice' and no terminal to retry"
    fi
  done
}

maybe_choose_uninstall_level() {
  if [[ -n "$UNINSTALL_LEVEL" ]]; then
    return 0
  fi
  if [[ "$INTERACTIVE" -eq 1 ]]; then
    choose_uninstall_level
  else
    UNINSTALL_LEVEL='standard'
  fi
}

set_uninstall_level() {
  case "$1" in
    stop|standard|full) UNINSTALL_LEVEL="$1" ;;
    *) die "invalid uninstall level '$1' (stop, standard or full)" ;;
  esac
}

container_exists() {
  command -v docker >/dev/null 2>&1 || return 1
  docker ps -a --format '{{.Names}}' 2>/dev/null | grep -qx 'lain'
}

stop_container() {
  local compose_file="${COMPOSE_DIR}/docker-compose.yml"
  if [[ -f "$compose_file" ]] && docker_ready; then
    if confirm "Stop the lain container now (docker compose down)?" y; then
      if compose_run down; then
        ok "Container stopped"
        return 0
      fi
      warn "docker compose down failed; stop it manually: cd \"${COMPOSE_DIR}\" && docker compose down"
    fi
  elif ! docker_ready; then
    info "Docker is not available; skipping container stop"
  fi
  if container_exists; then
    if confirm "Remove the 'lain' container (docker rm -f lain)?" y; then
      if docker rm -f lain >/dev/null 2>&1; then
        ok "Removed container lain"
      else
        warn "could not remove the container; run: docker rm -f lain"
      fi
    fi
  fi
  return 0
}

disable_user_service() {
  local unit_file="${HOME}/.config/systemd/user/lain.service"
  if [[ ! -f "$unit_file" ]]; then
    return 0
  fi
  if ! command -v systemctl >/dev/null 2>&1; then
    info "systemctl not available; the user service (if enabled) stays as-is"
    return 0
  fi
  if confirm "Stop and disable the lain user service?" y; then
    systemctl --user disable --now lain.service || warn "could not stop the service; run: systemctl --user disable --now lain.service"
    systemctl --user daemon-reload || warn "could not reload systemd; run: systemctl --user daemon-reload"
  fi
  return 0
}

remove_install_bin() {
  local bin="$1" label="$2" default_answer="$3"
  if [[ -z "$bin" || "$bin" != "${INSTALL_DIR}/"* || ! -f "$bin" ]]; then
    return 0
  fi
  if confirm "Remove $bin ($label)?" "$default_answer"; then
    if rm -f -- "$bin"; then
      ok "Removed $bin"
    else
      warn "could not remove $bin"
    fi
  else
    info "kept $bin; remove it manually with: rm -f -- '$bin'"
  fi
  return 0
}

remove_desktop_integration() {
  local desktop_file="${HOME}/.local/share/applications/lain-desktop.desktop"
  local desktop_icon="${HOME}/.local/share/icons/hicolor/256x256/apps/lain-desktop.png"
  if [[ -f "$desktop_file" ]] && grep -qF "$GENERATED_MARKER" "$desktop_file"; then
    remove_generated "$desktop_file"
    if [[ -f "$desktop_icon" ]]; then
      if rm -f -- "$desktop_icon"; then
        ok "Removed $desktop_icon"
      else
        warn "could not remove $desktop_icon"
      fi
    fi
    if command -v update-desktop-database >/dev/null 2>&1; then
      update-desktop-database "${HOME}/.local/share/applications" || true
    fi
  else
    info "no installer-managed desktop entry at $desktop_file"
  fi
  return 0
}

remove_server_image() {
  local image="${DOCKER_IMAGE}:${VERSION}"
  if ! command -v docker >/dev/null 2>&1; then
    info "Docker is not available; skipping image removal"
    return 0
  fi
  if [[ "$REMOVE_IMAGE" -eq 1 ]]; then
    : # explicit flag: proceed without a second prompt
  elif [[ "$INTERACTIVE" -eq 1 ]]; then
    confirm "Remove the server image ${image}?" n || return 0
  else
    return 0
  fi
  if docker rmi "$image" >/dev/null 2>&1; then
    ok "Removed image $image"
  else
    warn "could not remove $image (in use or already gone)"
  fi
  return 0
}

# dir_contains PARENT CHILD -- true when CHILD is PARENT or below it.
dir_contains() {
  local parent="${1%/}" child="$2"
  [[ -n "$parent" && -n "$child" ]] || return 1
  [[ "$child" == "$parent" || "$child" == "$parent/"* ]]
}

safe_purge_dir() {
  local dir="$1" media='' unsafe=''
  if [[ -z "$dir" || "$dir" != /* || "$dir" == '/' ]]; then
    warn "refusing to erase unsafe path: '${dir:-<empty>}'"
    return 1
  fi
  for unsafe in "$HOME" /home /root /etc /usr /var /opt /srv /mnt /media /data /tmp; do
    if [[ "$dir" == "$unsafe" ]]; then
      warn "refusing to erase '$dir' (too broad)"
      return 1
    fi
  done
  for media in "${MEDIA_DIRS[@]}"; do
    [[ -n "$media" ]] || continue
    if dir_contains "$dir" "$media" || dir_contains "$media" "$dir"; then
      warn "refusing to erase '$dir' (overlaps media directory '$media'); media is never touched"
      return 1
    fi
  done
  return 0
}

purge_dir_contents() {
  local dir="$1"
  safe_purge_dir "$dir" || return 1
  if [[ ! -e "$dir" ]]; then
    info "data directory does not exist: $dir"
    return 0
  fi
  if [[ ! -d "$dir" ]]; then
    warn "not a directory, keeping it: $dir"
    return 1
  fi
  if find "$dir" -mindepth 1 -delete; then
    ok "Erased contents of $dir (the directory itself was kept)"
  else
    warn "could not fully erase $dir"
    return 1
  fi
  return 0
}

confirm_purge_data() {
  local typed='' size=''
  if [[ -d "$DATA_DIR" ]]; then
    size="$(du -sh -- "$DATA_DIR" 2>/dev/null | cut -f1)"
    if [[ -n "$size" ]]; then
      info "data directory $DATA_DIR currently uses $size"
    fi
  fi
  warn "Full cleanup erases the database, cache and thumbnails in $DATA_DIR."
  info "Media files are never touched."
  if [[ "$PURGE_DATA" -eq 1 ]]; then
    return 0
  fi
  if [[ "$INTERACTIVE" -eq 0 ]]; then
    die "refusing to erase $DATA_DIR without confirmation (re-run interactively or pass --purge-data)"
  fi
  printf 'Type the data directory path to confirm erasure: ' >&2
  IFS= read -r typed < /dev/tty || return 1
  if [[ "$typed" != "$DATA_DIR" ]]; then
    warn "confirmation did not match; keeping $DATA_DIR"
    return 1
  fi
  return 0
}

remove_compose_backups() {
  local backup='' count=0
  local -a patterns=()
  patterns=("${COMPOSE_DIR}"/docker-compose.yml.bak.* "${COMPOSE_DIR}"/.env.bak.*)
  for backup in "${patterns[@]}"; do
    [[ -e "$backup" ]] || continue
    if rm -f -- "$backup"; then
      count=$((count + 1))
    else
      warn "could not remove $backup"
    fi
  done
  if ((count > 0)); then
    ok "Removed $count backup file(s) in ${COMPOSE_DIR}"
  fi
  return 0
}

remove_empty_dir() {
  local dir="$1"
  if [[ -z "$dir" || "$dir" == '/' ]]; then
    return 0
  fi
  if rmdir -- "$dir" 2>/dev/null; then
    ok "Removed empty $dir"
  fi
  return 0
}

uninstall_all() {
  local compose_file="${COMPOSE_DIR}/docker-compose.yml"
  local env_file="${COMPOSE_DIR}/.env"
  local unit_file="${HOME}/.config/systemd/user/lain.service"
  local desktop_bin="${INSTALL_DIR}/lain-desktop"
  local server_bin="${INSTALL_DIR}/lain"
  maybe_choose_uninstall_level
  step "Uninstall (${UNINSTALL_LEVEL})"
  info "Compose: ${compose_file}"
  info "Data: ${DATA_DIR} (media is never touched)"
  stop_container
  disable_user_service
  if [[ "$UNINSTALL_LEVEL" == 'stop' ]]; then
    info "stopped only; everything is still installed"
    info "resume with: cd \"${COMPOSE_DIR}\" && docker compose up -d"
    return 0
  fi
  if [[ -f "$compose_file" ]] && grep -qF "$GENERATED_MARKER" "$compose_file"; then
    remove_generated "$compose_file"
  else
    info "no installer-managed compose file at $compose_file"
  fi
  remove_generated "$env_file"
  if [[ -f "$unit_file" ]] && grep -qF "$GENERATED_MARKER" "$unit_file"; then
    remove_generated "$unit_file"
  else
    info "no installer-managed systemd unit at $unit_file"
  fi
  remove_desktop_integration
  remove_install_bin "$desktop_bin" 'desktop client' y
  remove_install_bin "$server_bin" 'server CLI' n
  remove_server_image
  if [[ "$UNINSTALL_LEVEL" == 'full' ]]; then
    if confirm_purge_data && purge_dir_contents "$DATA_DIR"; then
      :
    else
      warn "data directory kept: $DATA_DIR"
    fi
    remove_compose_backups
    remove_empty_dir "$COMPOSE_DIR"
    remove_empty_dir "$DATA_DIR"
  else
    info "data directory kept: $DATA_DIR"
  fi
  return 0
}

# --- Summary ---------------------------------------------------------------

print_summary() {
  local item=''
  step "Summary"
  if ((${#SUMMARY[@]} > 0)); then
    for item in "${SUMMARY[@]}"; do
      printf '  - %s\n' "$item"
    done
  fi
  if ((${#FAILURES[@]} > 0)); then
    printf '\n'
    warn "steps that did not complete:"
    for item in "${FAILURES[@]}"; do
      printf '  - %s\n' "$item" >&2
    done
  fi
  if ((${#NEXT_STEPS[@]} > 0)); then
    printf '\nNext steps:\n'
    for item in "${NEXT_STEPS[@]}"; do
      printf '  - %s\n' "$item"
    done
  fi
  printf '\nCleanup later with: %s --uninstall (levels: stop, standard, full)\n' "${SCRIPT_PATH:-install.sh}"
}

# --- Argument parsing ------------------------------------------------------

usage() {
  cat <<'EOF'
lain installer -- server (Docker / binary / user daemon) and desktop client

Usage: install.sh [options]

With no options, an interactive menu asks what to install.

Components (default with --yes: --server):
  --server                Install the server
  --desktop               Install the desktop client
  --both                  Install the server and the desktop client
  --no-server             Skip the server
  --no-desktop            Skip the desktop client

Server options:
  --server-mode MODE      docker (recommended) | binary | daemon
                            docker  compose file + ghcr.io/enrell/lain
                            binary  static release binary in --install-dir
                            daemon  static binary + systemd --user service
  --data PATH             data directory (default: ~/.local/share/lain)
  --media PATH            media dir mounted read-only; repeatable
                          (default: ~/Videos when it exists)
  --port PORT             HTTP port (default: 9360)
  --compose-dir DIR       where docker-compose.yml is written (default: ~/.lain)

General options:
  --install-dir DIR       binary install directory (default: ~/.local/bin)
  --version TAG           release tag: latest, v0.1.0 or 0.1.0 (default: latest)
  -y, --yes               accept defaults; never prompt
  --uninstall[=LEVEL]     remove lain: stop (halt container/service, remove
                          nothing), standard (default: generated files and
                          installed binaries, data kept), full (also erases
                          the data directory contents)
  --uninstall-level LEVEL same as --uninstall=LEVEL
  --purge-data            allow non-interactive data erasure with full
  --remove-image          also remove the server container image
  -h, --help              show this help

Environment:
  NO_COLOR                disable colored output

Examples:
  install.sh                                      interactive
  install.sh --yes                                server via Docker, defaults
  install.sh --server --server-mode binary --yes
  install.sh --desktop --yes
  install.sh --uninstall --yes
  install.sh --uninstall=full            # stop + generated files + data (asks first)
EOF
}

parse_args() {
  while (($# > 0)); do
    case "$1" in
      --server) SERVER=1; shift ;;
      --desktop) DESKTOP=1; shift ;;
      --both) SERVER=1; DESKTOP=1; shift ;;
      --no-server) SERVER=0; shift ;;
      --no-desktop) DESKTOP=0; shift ;;
      --server-mode)
        if (($# < 2)) || [[ -z "$2" ]]; then
          die "--server-mode needs a value (docker, binary or daemon)"
        fi
        MODE="$2"
        shift 2
        ;;
      --server-mode=*)
        MODE="${1#*=}"
        if [[ -z "$MODE" ]]; then
          die "--server-mode needs a value (docker, binary or daemon)"
        fi
        shift
        ;;
      --media)
        if (($# < 2)) || [[ -z "$2" ]]; then
          die "--media needs a non-empty path"
        fi
        MEDIA_DIRS+=("$2")
        MEDIA_GIVEN=1
        shift 2
        ;;
      --media=*)
        if [[ -z "${1#*=}" ]]; then
          die "--media needs a non-empty path"
        fi
        MEDIA_DIRS+=("${1#*=}")
        MEDIA_GIVEN=1
        shift
        ;;
      --data)
        if (($# < 2)) || [[ -z "$2" ]]; then
          die "--data needs a non-empty path"
        fi
        DATA_DIR="$2"
        DATA_SET=1
        shift 2
        ;;
      --data=*)
        if [[ -z "${1#*=}" ]]; then
          die "--data needs a non-empty path"
        fi
        DATA_DIR="${1#*=}"
        DATA_SET=1
        shift
        ;;
      --port)
        if (($# < 2)) || [[ -z "$2" ]]; then
          die "--port needs a value"
        fi
        PORT="$2"
        PORT_SET=1
        shift 2
        ;;
      --port=*)
        if [[ -z "${1#*=}" ]]; then
          die "--port needs a value"
        fi
        PORT="${1#*=}"
        PORT_SET=1
        shift
        ;;
      --install-dir)
        if (($# < 2)) || [[ -z "$2" ]]; then
          die "--install-dir needs a non-empty path"
        fi
        INSTALL_DIR="$2"
        INSTALL_SET=1
        shift 2
        ;;
      --install-dir=*)
        if [[ -z "${1#*=}" ]]; then
          die "--install-dir needs a non-empty path"
        fi
        INSTALL_DIR="${1#*=}"
        INSTALL_SET=1
        shift
        ;;
      --compose-dir)
        if (($# < 2)) || [[ -z "$2" ]]; then
          die "--compose-dir needs a non-empty path"
        fi
        COMPOSE_DIR="$2"
        COMPOSE_SET=1
        shift 2
        ;;
      --compose-dir=*)
        if [[ -z "${1#*=}" ]]; then
          die "--compose-dir needs a non-empty path"
        fi
        COMPOSE_DIR="${1#*=}"
        COMPOSE_SET=1
        shift
        ;;
      --version)
        if (($# < 2)) || [[ -z "$2" ]]; then
          die "--version needs a value"
        fi
        VERSION="$2"
        VERSION_SET=1
        shift 2
        ;;
      --version=*)
        if [[ -z "${1#*=}" ]]; then
          die "--version needs a value"
        fi
        VERSION="${1#*=}"
        VERSION_SET=1
        shift
        ;;
      -y|--yes) ASSUME_YES=1; shift ;;
      --uninstall-level)
        if (($# < 2)) || [[ -z "$2" ]]; then
          die "--uninstall-level needs a value (stop, standard or full)"
        fi
        UNINSTALL=1
        set_uninstall_level "$2"
        shift 2
        ;;
      --uninstall-level=*)
        if [[ -z "${1#*=}" ]]; then
          die "--uninstall-level needs a value (stop, standard or full)"
        fi
        UNINSTALL=1
        set_uninstall_level "${1#*=}"
        shift
        ;;
      --uninstall) UNINSTALL=1; shift ;;
      --uninstall=*)
        if [[ -z "${1#*=}" ]]; then
          die "--uninstall needs a value (stop, standard or full)"
        fi
        UNINSTALL=1
        set_uninstall_level "${1#*=}"
        shift
        ;;
      --purge-data) PURGE_DATA=1; shift ;;
      --remove-image) REMOVE_IMAGE=1; shift ;;
      -h|--help) usage; exit 0 ;;
      --) shift; break ;;
      *) die "unknown option: $1 (try --help)" ;;
    esac
  done
  if (($# > 0)); then
    die "unexpected argument(s): $*"
  fi
}

detect_interactive() {
  INTERACTIVE=0
  if [[ "$ASSUME_YES" -eq 0 ]]; then
    # Probe for a usable controlling terminal without leaking the probe's
    # stderr redirect into the shell (a bare "exec 3<>/dev/tty 2>/dev/null"
    # would permanently redirect this script's stderr to /dev/null).
    if : 2>/dev/null < /dev/tty; then
      INTERACTIVE=1
    fi
  fi
  if [[ "$ASSUME_YES" -eq 0 && "$INTERACTIVE" -eq 0 ]]; then
    warn "no terminal available; using defaults (same as --yes)"
    ASSUME_YES=1
  fi
}

# --- Main ------------------------------------------------------------------

main() {
  parse_args "$@"
  # ${#BASH_SOURCE[@]} is safe under set -u; indexing element 0 of an
  # empty BASH_SOURCE (piped via stdin) is not.
  local self="$0"
  if ((${#BASH_SOURCE[@]} > 0)); then
    self="${BASH_SOURCE[0]}"
  fi
  if [[ "$self" == /* ]]; then
    SCRIPT_PATH="$self"
  elif [[ -n "$self" && -f "$self" ]]; then
    SCRIPT_PATH="${PWD}/${self}"
  else
    SCRIPT_PATH='install.sh'
  fi
  trap cleanup EXIT
  trap 'exit 130' INT
  trap 'exit 143' TERM
  detect_interactive
  detect_compose || true
  normalize_paths
  if [[ "$UNINSTALL" -eq 1 ]]; then
    uninstall_all
    exit 0
  fi
  if [[ -z "$SERVER" && -z "$DESKTOP" ]]; then
    if [[ "$INTERACTIVE" -eq 1 ]]; then
      choose_components
      if [[ "$UNINSTALL" -eq 1 ]]; then
        uninstall_all
        exit 0
      fi
    else
      SERVER=1
      DESKTOP=0
    fi
  fi
  local want_server="${SERVER:-0}"
  local want_desktop="${DESKTOP:-0}"
  if [[ "$want_server" -eq 0 && "$want_desktop" -eq 0 ]]; then
    die "nothing selected (use --server, --desktop or --both)"
  fi
  if [[ "$want_server" -eq 1 && -z "$MODE" ]]; then
    if [[ "$INTERACTIVE" -eq 1 ]]; then
      choose_server_mode
    else
      MODE='docker'
    fi
  fi
  if [[ "$want_server" -eq 1 ]]; then
    case "$MODE" in
      docker|binary|daemon) ;;
      *) die "invalid server mode '$MODE' (docker, binary or daemon)" ;;
    esac
  fi
  validate_version
  validate_port
  if [[ "$want_server" -eq 1 ]]; then
    if [[ "$MODE" == 'docker' ]]; then
      configure_docker
    else
      configure_server_binary
    fi
  fi
  if [[ "$want_desktop" -eq 1 ]]; then
    configure_desktop
  fi
  validate_version
  validate_port
  normalize_paths
  if [[ "$want_server" -eq 1 && "$MEDIA_GIVEN" -eq 1 && "$MODE" != 'docker' ]]; then
    warn "--media only applies to Docker mode; the binary reads local paths directly"
  fi
  local rc=0
  if [[ "$want_server" -eq 1 ]]; then
    case "$MODE" in
      docker)
        if ! install_server_docker; then
          FAILURES+=('server (Docker)')
          rc=1
        fi
        ;;
      binary)
        if ! install_server_binary; then
          FAILURES+=('server (binary)')
          rc=1
        fi
        ;;
      daemon)
        if ! install_server_daemon; then
          FAILURES+=('server (daemon)')
          rc=1
        fi
        ;;
    esac
  fi
  if [[ "$want_desktop" -eq 1 ]]; then
    if ! install_desktop; then
      FAILURES+=('desktop client')
      rc=1
    fi
  fi
  print_summary
  if [[ "$rc" -ne 0 ]]; then
    exit 1
  fi
}

if ((${#BASH_SOURCE[@]} == 0)); then
  main "$@" # piped via stdin (curl ... | bash): no file to source
elif [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  main "$@"
fi
