"""Installer regressions. No Docker daemon or installed server is touched."""
import json
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
import os
import pty
import select
import time
from pathlib import Path
import subprocess
import tempfile
import threading
import unittest

SCRIPT = Path(__file__).with_name("install.sh")


class InstallerTests(unittest.TestCase):
    def bash(self, code, **env):
        return subprocess.run(
            ["bash", "-c", 'source "$INSTALL_SCRIPT"; ' + code],
            env={**os.environ, "INSTALL_SCRIPT": str(SCRIPT), **env},
            text=True, capture_output=True, check=True,
        ).stdout

    def test_default_media_survives_prompt(self):
        with tempfile.TemporaryDirectory() as root:
            self.assertEqual(self.bash('''
                ASSUME_YES=1; DEFAULT_MEDIA_DIR="$ROOT"; COMPOSE_DIR="$ROOT"
                DATA_SET=1; COMPOSE_SET=1; PORT_SET=1; VERSION_SET=1
                configure_docker
                printf '%s' "${MEDIA_DIRS[0]}"
            ''', ROOT=root), root)

    def test_compose_is_editable_and_backed_up(self):
        with tempfile.TemporaryDirectory() as root:
            compose = Path(root, "docker-compose.yml")
            original = '# Generated by lain install.sh\n# user-added volume\n'
            compose.write_text(original)
            self.bash('''
                COMPOSE_DIR="$ROOT"; DATA_DIR="$ROOT/data"
                write_compose_file example:latest "$ROOT/Films:/media/films:ro"
            ''', ROOT=root)
            self.assertNotIn("do not edit", compose.read_text())
            self.assertIn("/media/films:ro", compose.read_text())
            backups = list(Path(root).glob("docker-compose.yml.bak.*"))
            self.assertEqual(len(backups), 1)
            self.assertEqual(backups[0].read_text(), original)

    def test_legacy_compose_defaults_to_regeneration(self):
        with tempfile.TemporaryDirectory() as root:
            Path(root, 'docker-compose.yml').write_text(
                '# Generated by lain install.sh -- do not edit; re-run the installer to regenerate.\n'
            )
            result = self.bash('''
                COMPOSE_DIR="$ROOT"; COMPOSE_SET=1
                DATA_SET=1; PORT_SET=1; VERSION_SET=1; MEDIA_GIVEN=1
                confirm() { [[ "$2" == y ]]; }
                configure_docker
                printf '%s' "$REUSE_COMPOSE"
            ''', ROOT=root)
            self.assertTrue(result.endswith('0'))

    def test_explicit_media_defaults_to_regeneration(self):
        with tempfile.TemporaryDirectory() as root:
            Path(root, 'docker-compose.yml').write_text(
                '# Generated by lain install.sh -- yours to audit and edit.\n'
            )
            result = self.bash('''
                COMPOSE_DIR="$ROOT"; COMPOSE_SET=1
                DATA_SET=0; PORT_SET=0; VERSION_SET=0; MEDIA_GIVEN=1
                confirm() { [[ "$2" == y ]]; }
                prompt_path() { printf -v "$1" '%s' "$3"; }
                prompt() { printf -v "$1" '%s' "$3"; }
                configure_docker
                printf '%s' "$REUSE_COMPOSE"
            ''', ROOT=root)
            self.assertTrue(result.endswith('0'))

    def test_json_roundtrip(self):
        value = 'a "quote", backslash \\ and\nnewline $HOME'
        result = self.bash('json_object username admin password "$VALUE"', VALUE=value)
        self.assertEqual(json.loads(result), {"username": "admin", "password": value})

    def test_desktop_install_includes_icon_and_identity(self):
        with tempfile.TemporaryDirectory() as root:
            fake = Path(root, "lain")
            fake.write_text("#!/bin/sh\nexit 0\n")
            fake.chmod(0o755)
            icon = Path(root, "lain-desktop.png")
            icon.write_bytes(b"test-icon")
            self.bash('''
                HOME="$ROOT/home"; INSTALL_DIR="$ROOT/bin"; TMP_DIR="$ROOT/tmp"
                mkdir -p "$TMP_DIR"
                warn_if_missing_libs() { :; }
                check_path() { :; }
                install_desktop_binary "$ROOT/lain" binary "$ROOT/lain-desktop.png"
            ''', ROOT=root)
            desktop = Path(root, "home/.local/share/applications/lain-desktop.desktop")
            installed_icon = Path(
                root, "home/.local/share/icons/hicolor/256x256/apps/lain-desktop.png"
            )
            self.assertIn("Name=Lain\n", desktop.read_text())
            self.assertIn("Icon=lain-desktop\n", desktop.read_text())
            self.assertIn("StartupWMClass=lain-desktop\n", desktop.read_text())
            self.assertEqual(installed_icon.read_bytes(), b"test-icon")

    def test_appimage_icon_extraction_marks_download_executable(self):
        # Regression: curl downloads land 0644, so --appimage-extract fails
        # unless the installer marks the image executable first.
        with tempfile.TemporaryDirectory() as root:
            fake = Path(root, "lain-desktop_0.2.0.AppImage")
            fake.write_text(
                "#!/bin/sh\n"
                'if [ "$1" = "--appimage-extract" ]; then\n'
                '  mkdir -p "squashfs-root/usr/share/icons/hicolor/256x256/apps"\n'
                '  printf "fake-icon" > "squashfs-root/usr/share/icons/hicolor/256x256/apps/lain-desktop.png"\n'
                "fi\n"
            )
            fake.chmod(0o644)
            self.bash('''
                HOME="$ROOT/home"; INSTALL_DIR="$ROOT/bin"; TMP_DIR="$ROOT/tmp"
                mkdir -p "$TMP_DIR"
                warn_if_missing_libs() { :; }
                check_path() { :; }
                install_desktop_binary "$ROOT/lain-desktop_0.2.0.AppImage" appimage
            ''', ROOT=root)
            installed_icon = Path(
                root, "home/.local/share/icons/hicolor/256x256/apps/lain-desktop.png"
            )
            self.assertEqual(installed_icon.read_bytes(), b"fake-icon")

    def test_nested_mount_mapping_and_boundary(self):
        result = self.bash('''
            WIZARD_HOSTS=(/library /library/Films)
            WIZARD_PATHS=(/media/all /media/films)
            container_path /library/Films/Drama
            if container_path /library-other; then exit 1; fi
        ''')
        self.assertEqual(result.strip(), "/media/films/Drama")

    def test_readline_completes_directory_with_spaces(self):
        with tempfile.TemporaryDirectory() as root:
            media = Path(root, 'Films Archive')
            media.mkdir()
            pid, fd = pty.fork()
            if pid == 0:
                os.execve('/bin/bash', ['bash', '-c', '''
                    source "$INSTALL_SCRIPT"
                    prompt_path selected Directory ''
                    printf '\\nRESULT=<%s>\\n' "$selected"
                '''], {**os.environ, 'INSTALL_SCRIPT': str(SCRIPT), 'TERM': 'dumb'})
            output = b''
            sent = False
            try:
                deadline = time.monotonic() + 5
                while time.monotonic() < deadline:
                    if not select.select([fd], [], [], 0.1)[0]:
                        continue
                    try:
                        chunk = os.read(fd, 65536)
                    except OSError:
                        break
                    if not chunk:
                        break
                    output += chunk
                    if not sent and b'clear to skip): ' in output:
                        os.write(fd, (root + '/Films\t\n').encode())
                        sent = True
                    if b'RESULT=<' in output:
                        break
                self.assertIn(f'RESULT=<{media}/>'.encode(), output)
            finally:
                os.close(fd)
                os.waitpid(pid, 0)

    def test_wizard_setup_and_rerun(self):
        requests = []
        libraries = []
        accounts = []
        secret = 'long "password" with \\ and $dollars'

        class API(BaseHTTPRequestHandler):
            def log_message(self, *args):
                pass

            def do_GET(self):
                self.respond()

            def do_POST(self):
                self.respond()

            def respond(self):
                raw = self.rfile.read(int(self.headers.get('Content-Length', 0)))
                body = json.loads(raw) if raw else None
                requests.append((self.command, self.path, body))
                status = 200
                if self.path == '/api/setup/status':
                    result = {'setup_required': not accounts}
                elif self.path == '/api/setup':
                    accounts.append(body)
                    result, status = {'id': 'admin'}, 201
                elif self.path == '/api/auth/login':
                    result = {'token': 'test-token'}
                    if body != {'username': 'admin', 'password': secret}:
                        result, status = {'error': 'bad credentials'}, 401
                elif self.headers.get('Authorization') != 'Bearer test-token':
                    result, status = {'error': 'unauthorized'}, 401
                elif self.path == '/api/me':
                    result = {'role': 'admin'}
                elif self.path == '/api/libraries' and self.command == 'GET':
                    result = libraries
                elif self.path == '/api/libraries':
                    libraries.append(body)
                    result, status = body, 201
                elif self.path == '/api/library/scan':
                    result, status = {'state': 'running'}, 202
                else:
                    result, status = {'error': 'unknown endpoint'}, 404
                encoded = json.dumps(result).encode()
                self.send_response(status)
                self.send_header('Content-Type', 'application/json')
                self.send_header('Content-Length', str(len(encoded)))
                self.end_headers()
                self.wfile.write(encoded)

        server = ThreadingHTTPServer(('127.0.0.1', 0), API)
        thread = threading.Thread(target=server.serve_forever, daemon=True)
        thread.start()
        try:
            with tempfile.TemporaryDirectory() as root:
                Path(root, 'Films Archive').mkdir()
                for _ in range(2):
                    output = self.bash('''
                        WIZARD_URL="$URL"; WIZARD_HOSTS=("$ROOT"); WIZARD_PATHS=(/media/videos)
                        COUNT=0
                        prompt_password() { printf -v "$1" '%s' "$SECRET"; }
                        prompt_path() { printf -v "$1" '%s' "$ROOT/Films Archive"; }
                        prompt() { printf -v "$1" '%s' "$3"; }
                        confirm() {
                            if [[ "$1" == 'Register a library now?' ]]; then
                                COUNT=$((COUNT + 1)); [[ "$COUNT" == 1 ]]; return
                            fi
                            return 0
                        }
                        trap cleanup EXIT
                        terminal_wizard
                    ''', ROOT=root, SECRET=secret, URL=f'http://127.0.0.1:{server.server_port}')
                    self.assertNotIn(secret, output)
                    self.assertNotIn('test-token', output)
                self.assertEqual(len(accounts), 1)
                self.assertEqual(accounts[0]['password'], secret)
                self.assertEqual(libraries, [{
                    'name': 'Films Archive', 'type': 'anime', 'path': '/media/videos/Films Archive',
                }])
                self.assertEqual(sum(path == '/api/library/scan' for _, path, _ in requests), 2)
        finally:
            server.shutdown()
            server.server_close()
            thread.join()

    def test_uninstall_level_flags(self):
        self.assertEqual(self.bash('''
            parse_args --uninstall-level full
            printf '%s/%s' "$UNINSTALL" "$UNINSTALL_LEVEL"
        '''), '1/full')
        self.assertEqual(self.bash('''
            parse_args --uninstall=stop
            printf '%s/%s' "$UNINSTALL" "$UNINSTALL_LEVEL"
        '''), '1/stop')

    def test_uninstall_invalid_level(self):
        proc = subprocess.run(
            ["bash", "-c", 'source "$INSTALL_SCRIPT"; parse_args --uninstall-level bogus'],
            env={**os.environ, "INSTALL_SCRIPT": str(SCRIPT)},
            text=True, capture_output=True,
        )
        self.assertNotEqual(proc.returncode, 0)

    def make_uninstall_tree(self, root):
        root = Path(root)
        home = root / "home"
        (home / ".config/systemd/user").mkdir(parents=True)
        (home / ".local/share/applications").mkdir(parents=True)
        (home / ".local/share/icons/hicolor/256x256/apps").mkdir(parents=True)
        marker = "# Generated by lain install.sh\n"
        (home / ".config/systemd/user/lain.service").write_text(marker + "[Unit]\n")
        (home / ".local/share/applications/lain-desktop.desktop").write_text(
            marker + "[Desktop Entry]\n"
        )
        (home / ".local/share/icons/hicolor/256x256/apps/lain-desktop.png").write_bytes(b"icon")
        compose = root / "compose"
        compose.mkdir()
        (compose / "docker-compose.yml").write_text(marker + "services:\n")
        (compose / ".env").write_text(marker + "UID=1000\n")
        (compose / "docker-compose.yml.bak.20240101000000.1").write_text("backup\n")
        bindir = root / "bin"
        bindir.mkdir()
        (bindir / "lain-desktop").write_text("desktop")
        (bindir / "lain").write_text("server")
        data = root / "data"
        (data / "cache").mkdir(parents=True)
        (data / "lain.db").write_text("db")
        (data / ".hidden").write_text("dot")
        (data / "cache/thumb.jpg").write_text("thumb")
        media = root / "media"
        media.mkdir()
        (media / "film.mkv").write_text("media")
        return {"home": home, "compose": compose, "bin": bindir, "data": data, "media": media}

    def uninstall_prelude(self):
        return '''
            HOME="$ROOT/home"; COMPOSE_DIR="$ROOT/compose"; INSTALL_DIR="$ROOT/bin"
            DATA_DIR="$ROOT/data"; MEDIA_DIRS=()
            ASSUME_YES=1; INTERACTIVE=0
            docker_ready() { return 1; }
            container_exists() { return 1; }
            confirm() { [[ "$2" == y ]]; }
        '''

    def test_uninstall_standard_keeps_data_and_media(self):
        with tempfile.TemporaryDirectory() as root:
            paths = self.make_uninstall_tree(root)
            self.bash(self.uninstall_prelude() + 'UNINSTALL_LEVEL=standard; uninstall_all', ROOT=root)
            self.assertFalse((paths["compose"] / "docker-compose.yml").exists())
            self.assertFalse((paths["compose"] / ".env").exists())
            self.assertFalse((paths["home"] / ".config/systemd/user/lain.service").exists())
            self.assertFalse(
                (paths["home"] / ".local/share/applications/lain-desktop.desktop").exists()
            )
            self.assertFalse(
                (paths["home"] / ".local/share/icons/hicolor/256x256/apps/lain-desktop.png").exists()
            )
            self.assertFalse((paths["bin"] / "lain-desktop").exists())
            self.assertTrue((paths["bin"] / "lain").exists())
            self.assertTrue((paths["data"] / "lain.db").exists())
            self.assertTrue((paths["media"] / "film.mkv").exists())

    def test_uninstall_full_purges_data(self):
        with tempfile.TemporaryDirectory() as root:
            paths = self.make_uninstall_tree(root)
            self.bash(
                self.uninstall_prelude()
                + 'UNINSTALL_LEVEL=full; PURGE_DATA=1; uninstall_all',
                ROOT=root,
            )
            self.assertFalse((paths["compose"] / "docker-compose.yml").exists())
            self.assertFalse((paths["compose"] / "docker-compose.yml.bak.20240101000000.1").exists())
            self.assertFalse(paths["compose"].exists())
            self.assertFalse(paths["data"].exists())
            self.assertTrue((paths["media"] / "film.mkv").exists())
            self.assertTrue((paths["bin"] / "lain").exists())

    def test_uninstall_stop_removes_nothing(self):
        with tempfile.TemporaryDirectory() as root:
            paths = self.make_uninstall_tree(root)
            self.bash(self.uninstall_prelude() + 'UNINSTALL_LEVEL=stop; uninstall_all', ROOT=root)
            self.assertTrue((paths["compose"] / "docker-compose.yml").exists())
            self.assertTrue((paths["compose"] / ".env").exists())
            self.assertTrue((paths["home"] / ".config/systemd/user/lain.service").exists())
            self.assertTrue(
                (paths["home"] / ".local/share/applications/lain-desktop.desktop").exists()
            )
            self.assertTrue((paths["bin"] / "lain-desktop").exists())
            self.assertTrue((paths["bin"] / "lain").exists())
            self.assertTrue((paths["data"] / "lain.db").exists())

    def test_purge_refuses_unsafe_paths(self):
        with tempfile.TemporaryDirectory() as root:
            result = self.bash('''
                MEDIA_DIRS=("$ROOT/media")
                fail=0
                safe_purge_dir / || fail=$((fail+1))
                safe_purge_dir "$HOME" || fail=$((fail+1))
                safe_purge_dir "$ROOT/media" || fail=$((fail+1))
                safe_purge_dir "$ROOT/media/sub" || fail=$((fail+1))
                safe_purge_dir "$ROOT/data" || exit 1
                printf '%s' "$fail"
            ''', ROOT=root)
            self.assertEqual(result, '4')

    def test_purge_dir_contents_keeps_directory(self):
        with tempfile.TemporaryDirectory() as root:
            data = Path(root, "data")
            (data / "sub").mkdir(parents=True)
            (data / "a").write_text("a")
            (data / ".h").write_text("h")
            (data / "sub" / "b").write_text("b")
            self.bash('MEDIA_DIRS=(); purge_dir_contents "$ROOT/data"', ROOT=root)
            self.assertTrue(data.is_dir())
            self.assertEqual(list(data.iterdir()), [])


if __name__ == "__main__":
    unittest.main()
